FROM python:3.12.3
WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 && \
    pip install --no-cache-dir \
    transformers datasets accelerate evaluate Pillow
COPY data_prep.py /app/data_prep.py
CMD ["python", "data_prep.py"]
