FROM python:3.12.3
WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install --no-cache-dir \
	torch torchvision --index-url https://download.pytorch.org/whl/cpu && \
    pip install transformers datasets 'accelerate>=0.26.0'
COPY distilbert-bookcorpus-mlm-final /app/distilbert-bookcorpus-mlm-final
COPY infer.py /app/infer.py
CMD ["python", "infer.py"]
