FROM python:3.12.3
WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install --no-cache-dir \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 && \
    pip install --no-cache-dir \
    transformers datasets accelerate evaluate Pillow
COPY predict_only.py /app/predict_only.py
COPY vit_best_model.pth /app/vit_best_model.pth 
CMD ["python", "predict_only.py"]
